
export enum FileMenuType {
  DIR_ENTER,
  PREVIEW,
  DETAIL,
  RENAME,
  COPY,
  MOVE,
  CREATE_SHARE,
  DOWNLOAD,
  DELETE,
  MULTI_SELECT,
}

export enum MoreMenuType {
  MULTI_SELECT,
  SHOW_ICON,
  SHOW_LIST,
  NEW_DIR,
  NEW_FILE,
  UPLOAD_FILE,
  SORT_BY_TIME,
  SORT_BY_TYPE,
  SORT_BY_NAME,
  SORT_BY_SIZE,
}

export enum ShowType {
  SHOW_ICON,
  SHOW_LIST
}

export enum SortType {
  SORT_BY_TIME,
  SORT_BY_TYPE,
  SORT_BY_NAME,
  SORT_BY_SIZE,
}