export const USERPRIVDATA_NAME = 'UserPrivData'

export const WEBSITE_CURRENT_USER_KEY = 'current_user_key'

/**
 * 站点请求超时时间
 */
export const CLOUDREVE_REQUEST_TIMEOUT: number = 3000;

/**
 * 网站url前缀
 */
export const CLOUDREVE_URL_PREFIX:string = '/api/v3'

/**
 * 站点配置路径
 */
export const CLOUDREVE_CONFIG: string = '/site/config'

/**
 * 站点ping请求路径
 */
export const CLOUDREVE_PING: string = '/site/ping'

/**
 * 站点登录请求路径
 */
export const CLOUDREVE_LOGIN: string = '/user/session'

/**
 * 用户存储信息请求路径
 */
export const CLOUDREVE_USER_STORAGE: string = '/user/storage'