export const USERPRIVDATA_NAME = 'UserPrivData'

export const WEBSITE_PROTOCOL_KEY = 'website_protocol'
export const WEBSITE_URL_KEY = 'website_url'
export const WEBSITE_COOKIE_KEY = 'website_cookie'

/**
 * 站点请求超时时间
 */
export const CLOUDREVE_REQUEST_TIMEOUT: number = 3000;

/**
 * 网站url前缀
 */
export const CLOUDREVE_URL_PREFIX:string = '/api/v3'

/**
 * 站点配置路径
 */
export const CLOUDREVE_CONFIG: string = '/site/config'

/**
 * 站点ping请求路径
 */
export const CLOUDREVE_PING: string = '/site/ping'

/**
 * 站点登录请求路径
 */
export const CLOUDREVE_LOGIN: string = '/user/session'